/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectolatiendita;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OliverAmitahi
 */
public class Tienda extends javax.swing.JFrame {

    /**
     * Creates new form Tienda
     */
    public Tienda() {
        initComponents();
        iniciarComponentes();
        
        
       
    }

    public void iniciarComponentes()
    {
        
        DefaultListModel modelo = new DefaultListModel(); 
//        JScrollPane scrollLista = new JScrollPane();
//        scrollLista.setBounds(20, 120,220, 80);
//        scrollLista.setViewportView(ListaCategoria);
        modelo.addElement("Martillo");
        modelo.addElement("Sierra");
        modelo.addElement("Madera");
        modelo.addElement("Taladro");
        modelo.addElement("Clavos");
        ListaCategoria.setModel(modelo);
        
        
        
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaCategoria = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaProducto = new javax.swing.JList();
        TxtCodigo = new java.awt.TextField();
        TxtPrecio = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtCantidad = new java.awt.TextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Gungsuh", 0, 18)); // NOI18N
        jLabel1.setText("Productos");

        ListaCategoria.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        ListaCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaCategoriaMouseClicked(evt);
            }
        });
        ListaCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ListaCategoriaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(ListaCategoria);

        jLabel3.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        jLabel3.setText("Categoria");

        jLabel4.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        jLabel4.setText("Codigo");

        jLabel5.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        jLabel5.setText("Precio");

        jLabel7.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        jLabel7.setText("Producto");

        ListaProducto.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        ListaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaProductoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListaProducto);

        TxtCodigo.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        TxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodigoActionPerformed(evt);
            }
        });

        TxtPrecio.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        jButton1.setText("Añadir Al Carrito");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setToolTipText("");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jLabel6.setRequestFocusEnabled(false);
        jLabel6.setVerifyInputWhenFocusTarget(false);

        jLabel8.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        jLabel8.setText("Cantidad");

        TxtCantidad.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N

        jButton2.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        jButton2.setText("Ir a Factura");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(370, 370, 370)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(69, 69, 69))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(25, 25, 25)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(TxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(92, 92, 92))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigoActionPerformed

    private void ListaCategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ListaCategoriaKeyPressed
                // TODO add your handling code here:
    }//GEN-LAST:event_ListaCategoriaKeyPressed

    private void ListaCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaCategoriaMouseClicked
               // TODO add your handling code here:
           DefaultListModel modelopro = new DefaultListModel(); 
            
            if(ListaCategoria.getSelectedValue().toString().equals("Martillo"))
            { 
                modelopro.clear();
                modelopro.addElement("Martillo marca ACME");
                modelopro.addElement("Martillo marca PHILIPHS");
                ListaProducto.setModel(modelopro);
                
            }
            if(ListaCategoria.getSelectedValue().toString().equals("Sierra"))
            { 
                modelopro.clear();
                modelopro.addElement("Sierra marca STAHL");
                modelopro.addElement("Sierra marca FEHN");
                ListaProducto.setModel(modelopro);
                
            }
            if(ListaCategoria.getSelectedValue().toString().equals("Madera"))
            { 
                modelopro.clear();
                modelopro.addElement("Playwood");
                modelopro.addElement("Cedro");
                ListaProducto.setModel(modelopro);   
            }
            if(ListaCategoria.getSelectedValue().toString().equals("Taladro"))
            { 
                modelopro.clear();
                modelopro.addElement("Taladro marca ACME");
                modelopro.addElement("Taladro marca REIMS");
                ListaProducto.setModel(modelopro);   
            }
            if(ListaCategoria.getSelectedValue().toString().equals("Clavos"))
            { 
                modelopro.clear();
                modelopro.addElement("Clavo 1 pulg");
                modelopro.addElement("Clavo 1/2 pulg");
                ListaProducto.setModel(modelopro);   
            }
           
            
            
            
             
    }//GEN-LAST:event_ListaCategoriaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String codigo, DescProd, precio, cantidad, Subtotal = "";
        codigo = this.TxtCodigo.getText();
        cantidad = this.TxtCantidad.getText();
        precio = this.TxtPrecio.getText();
        DescProd=ListaProducto.getSelectedValue().toString();
        
        Factura fc = new Factura();
        fc.set_datos(codigo, DescProd, precio, cantidad);
// TODO add your handling code here:
//        DefaultTableModel tmodel = (DefaultTableModel) jTable2.getModel();
        float st = 0;
        DefaultTableModel tmodel = new DefaultTableModel();
        st = Float.parseFloat(TxtPrecio.getText())* Float.parseFloat(TxtCantidad.getText());
        tmodel.addRow(new Object[]{TxtCodigo.getText(), TxtPrecio.getText(), ListaProducto.getSelectedValue().toString(), TxtCantidad.getText(), String.valueOf(st)});
//        tmodel.addRow(new Object[]{TxtCodigo.getText(),TxtPrecio.getText(),ListaProducto.getSelectedValue(),TxtCantidad.getText()});
        
        fc.DibujarTabla(tmodel);
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Factura f = new Factura();
       f.show();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ListaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaProductoMouseClicked
        // TODO add your handling code here:
        if(ListaProducto.getSelectedValue().toString().equals("Martillo marca ACME"))
        {
            TxtCodigo.setText("001");
            TxtPrecio.setText("130.00");

            ImageIcon imagen = new ImageIcon("D:\\Users\\OliverAmitahi\\Desktop\\FERRE_SENACO\\001.jpg");
            Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_DEFAULT));
            jLabel6.setIcon(icono);

        }
        if(ListaProducto.getSelectedValue().toString().equals("Martillo marca PHILIPHS"))
        {
            TxtCodigo.setText("002");
            TxtPrecio.setText("110.00");
            ImageIcon imagen = new ImageIcon("D:\\Users\\OliverAmitahi\\Desktop\\FERRE_SENACO\\002.jpg");
            Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_DEFAULT));
            jLabel6.setIcon(icono);
        }
        if(ListaProducto.getSelectedValue().toString().equals("Sierra marca STAHL"))
        {
            TxtCodigo.setText("003");
            TxtPrecio.setText("450");
            ImageIcon imagen = new ImageIcon("D:\\Users\\OliverAmitahi\\Desktop\\FERRE_SENACO\\003.jpg");
            Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_DEFAULT));
            jLabel6.setIcon(icono);
        }
        if(ListaProducto.getSelectedValue().toString().equals("Sierra marca FEHN"))
        {
            TxtCodigo.setText("004");
            TxtPrecio.setText("239.00");
            ImageIcon imagen = new ImageIcon("D:\\Users\\OliverAmitahi\\Desktop\\FERRE_SENACO\\004.jpg");
            Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_DEFAULT));
            jLabel6.setIcon(icono);
        }
        if(ListaProducto.getSelectedValue().toString().equals("Playwood"))
        {
            TxtCodigo.setText("005");
            TxtPrecio.setText("345.00");
            ImageIcon imagen = new ImageIcon("D:\\Users\\OliverAmitahi\\Desktop\\FERRE_SENACO\\001.jpg");
            Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_DEFAULT));
            jLabel6.setIcon(icono);
        }
        if(ListaProducto.getSelectedValue().toString().equals("Cedro"))
        {
            TxtCodigo.setText("006");
            TxtPrecio.setText("602.00");
            ImageIcon imagen = new ImageIcon("D:\\Users\\OliverAmitahi\\Desktop\\FERRE_SENACO\\001.jpg");
            Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_DEFAULT));
            jLabel6.setIcon(icono);
        }
        if(ListaProducto.getSelectedValue().toString().equals("Taladro marca ACME"))
        {
            TxtCodigo.setText("007");
            TxtPrecio.setText("420.00");
            ImageIcon imagen = new ImageIcon("D:\\Users\\OliverAmitahi\\Desktop\\FERRE_SENACO\\007.jpg");
            Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_DEFAULT));
            jLabel6.setIcon(icono);
        }
        if(ListaProducto.getSelectedValue().toString().equals("Taladro marca REIMS"))
        {
            TxtCodigo.setText("008");
            TxtPrecio.setText("237.00");
            ImageIcon imagen = new ImageIcon("D:\\Users\\OliverAmitahi\\Desktop\\FERRE_SENACO\\008.jpg");
            Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_DEFAULT));
            jLabel6.setIcon(icono);
        }
        if(ListaProducto.getSelectedValue().toString().equals("Clavo 1 pulg"))
        {
            TxtCodigo.setText("009");
            TxtPrecio.setText("1.00");
            ImageIcon imagen = new ImageIcon("D:\\Users\\OliverAmitahi\\Desktop\\FERRE_SENACO\\009.jpg");
            Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_DEFAULT));
            jLabel6.setIcon(icono);
        }
        if(ListaProducto.getSelectedValue().toString().equals("Clavo 1/2 pulg"))
        {
            TxtCodigo.setText("010");
            TxtPrecio.setText("0.50");
            ImageIcon imagen = new ImageIcon("D:\\Users\\OliverAmitahi\\Desktop\\FERRE_SENACO\\010.jpg");
            Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_DEFAULT));
            jLabel6.setIcon(icono);
        }

    }//GEN-LAST:event_ListaProductoMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tienda().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListaCategoria;
    private javax.swing.JList ListaProducto;
    private java.awt.TextField TxtCantidad;
    private java.awt.TextField TxtCodigo;
    private java.awt.TextField TxtPrecio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
    



